### ISSUE TITLE
Ability to switch between todo lists

### ISSUE THREAD

**Issue by kbonnici** [kbonnici-todo/todo-frontend#11]
- [ ] Main app header component has a button which allows user to switch between their different todo lists
- [ ] Todo list dropdown is updated with currently selected todo list
- [ ] Todo list title is updated as well

Depends on #2, #3
